# Generated by Django 5.2.7 on 2025-10-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('ID_Videojuego', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=200)),
                ('Desarrollador', models.CharField(max_length=100)),
                ('Genero', models.CharField(max_length=50)),
                ('Plataforma', models.CharField(max_length=50)),
                ('Fecha_Lanzamiento', models.DateField()),
                ('ID_Proveedor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
            },
        ),
    ]
